name: Generate ERD

on:
  push:
    branches:
      - master

jobs:
  generate_erd:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Execute generate.sh script
        run: |
          chmod +x generate.sh
          ./generate.sh ${{ secrets.ENDPOINT }} ${{ secrets.X_API_HEADER }}
      
      - name: Render images for every Mermaid diagram in all Markdown files (*.md) in the repo
        uses: nielsvaneck/render-md-mermaid@v2

      - name: Commit rendered png and svg files
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          file_pattern: "*[.svg,.png]"
          commit_message: automatically rendered mermaid diagrams
      